### ISSUE TITLE
Formal equiv diff signed bin

### ISSUE THREAD

**Issue by alaindargelas** [antmicro/yosys-systemverilog#1029]
Test ./yosys/tests/simple/loop_var_shadow.v
Ran with ./run_formal_verif.sh test=simple_loop_var_shadow.v has a diff due to incorrect handling of signed binary values.
You'll need to merge 
https://github.com/chipsalliance/Surelog/pull/3188
and adapt the plugin code to use the pseudo algorithm described in the issue https://github.com/chipsalliance/Surelog/issues/3183

**Comment by rkapuscik** [comment]
This is passing now: https://github.com/antmicro/yosys-systemverilog/blob/master/formal/passlist.txt#L264
