### ISSUE TITLE
Formal equiv diff simple_scopes.v

### ISSUE THREAD

**Issue by alaindargelas** [antmicro/yosys-systemverilog#1137]
Test yosys/tests/simple_scopes.v
 ./run_formal_verif.sh test=simple_scopes.v

After fix: https://github.com/chipsalliance/Surelog/pull/3262 and https://github.com/chipsalliance/Surelog/pull/3263
One remaining issue in the plugin about the port  type of 'a' which is different from the Yosys AST version.
The result is a diffferent DSP setting in the gate level netlist. Yosys seems correct, and the plugin not.

![Screenshot from 2022-10-08 22-32-53](https://user-images.githubusercontent.com/63669492/194739814-94bb412a-6bfb-49c6-8af3-3a5e5b4004bb.png)

**Comment by alaindargelas** [comment]
![Screenshot from 2022-10-08 22-38-29](https://user-images.githubusercontent.com/63669492/194739913-b4ce98d2-de65-47c7-9b46-eb88d6b38e7b.png)

**Comment by wsipak** [comment]
Fixed here: https://github.com/chipsalliance/yosys-f4pga-plugins/pull/408
And present in the passlist for CI testing here: https://github.com/antmicro/yosys-systemverilog/blob/568e88746964c87fd1e3495b729a6e0ebcf81fdc/formal/passlist.txt#L266
